### ISSUE TITLE
[beta] component installation never ends

### ISSUE THREAD

**Issue by jeferson-cleancloud** [binxio/azure-devops-extensions#20]
While running the following command over ADO pipeline stage:
```
gcloud beta billing projects link $(gcOutProjectId) --billing-account "$(gcOutBillingProjectId)"
```
It returns that the [beta] component installation is required. And so it starts the installation, which never ends

![Pipelines - Run 20220716 4 logs (1)](https://user-images.githubusercontent.com/70276848/179380264-7c60f90a-ca56-417a-b5fd-7922019e9cab.png)

**Comment by laurensknoll** [comment]
Hi @jeferson-cleancloud

Thanks for reporting this. I'm not sure why the implicit install (using a beta command, whilst it is not available) fails. I expected it was missing a `--quiet`-flag, but that did not matter. Interestingly, also including the `--verbosity=debug`-flag does not yield any output. To be continued..

As a work around, please include an explicit beta components install step.

```yaml
steps:
steps:
- task: GoogleCloudSdkInstaller@0
  displayName: 'Install Google Cloud SDK 393.0.0'
  inputs:
    version: 393.0.0
- task: GcloudRunner@0
  displayName: 'gcloud components install beta'
  inputs:
    command: 'components install beta'
  enabled: false
steps:
- task: GcloudRunner@0
  displayName: 'gcloud beta projects list'
  inputs:
    command: 'beta projects list'
...
```
